package sudoku;

import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author laura
 */
public class NivelMedio1 extends javax.swing.JFrame {
    private PreencheBloco botaoBloco = new PreencheBloco();
    private DesafioOuIndividual escolhaUsuario = new DesafioOuIndividual();
    private Vitorias pontuacao = new Vitorias();
    private ExceptionBloco excecao = new ExceptionBloco();
    /**
     * Creates new form NivelMedio2
     */
    public NivelMedio1() {
        initComponents();
    }
    
    public NivelMedio1(String desafioOuIndividual) {
        initComponents();
        escolhaUsuario.desafioOuIndividual(desafioOuIndividual);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfBloco1 = new javax.swing.JTextField();
        tfBloco2 = new javax.swing.JTextField();
        tfBloco5 = new javax.swing.JTextField();
        tfBloco6 = new javax.swing.JTextField();
        tfBloco3 = new javax.swing.JTextField();
        tfBloco4 = new javax.swing.JTextField();
        tfBloco7 = new javax.swing.JTextField();
        tfBloco8 = new javax.swing.JTextField();
        tfBloco9 = new javax.swing.JTextField();
        tfBloco10 = new javax.swing.JTextField();
        tfBloco13 = new javax.swing.JTextField();
        tfBloco14 = new javax.swing.JTextField();
        tfBloco11 = new javax.swing.JTextField();
        tfBloco12 = new javax.swing.JTextField();
        tfBloco15 = new javax.swing.JTextField();
        tfBloco16 = new javax.swing.JTextField();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btnX = new javax.swing.JButton();
        btnVerificar = new javax.swing.JButton();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelIcon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nível 1");
        setMinimumSize(getPreferredSize());
        setPreferredSize(new java.awt.Dimension(550, 300));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tfBloco1.setEditable(false);
        tfBloco1.setBackground(new java.awt.Color(255, 255, 255));
        tfBloco1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tfBloco1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 255), 2, true));
        tfBloco1.setMinimumSize(new java.awt.Dimension(60, 40));
        tfBloco1.setPreferredSize(new java.awt.Dimension(60, 40));
        tfBloco1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tfBloco1MousePressed(evt);
            }
        });
        getContentPane().add(tfBloco1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, 60));

        tfBloco2.setEditable(false);
        tfBloco2.setBackground(new java.awt.Color(255, 255, 255));
        tfBloco2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tfBloco2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 255), 2, true));
        tfBloco2.setMinimumSize(new java.awt.Dimension(60, 40));
        tfBloco2.setPreferredSize(new java.awt.Dimension(60, 40));
        tfBloco2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tfBloco2MousePressed(evt);
            }
        });
        getContentPane().add(tfBloco2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 60, 60));

        tfBloco5.setEditable(false);
        tfBloco5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        tfBloco5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco5.setText("4");
        tfBloco5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 255), 2, true));
        tfBloco5.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        tfBloco5.setEnabled(false);
        tfBloco5.setMinimumSize(new java.awt.Dimension(60, 40));
        getContentPane().add(tfBloco5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 60, 60));

        tfBloco6.setEditable(false);
        tfBloco6.setBackground(new java.awt.Color(255, 255, 255));
        tfBloco6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tfBloco6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 255), 2, true));
        tfBloco6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tfBloco6MousePressed(evt);
            }
        });
        getContentPane().add(tfBloco6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 60, 60));

        tfBloco3.setEditable(false);
        tfBloco3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        tfBloco3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco3.setText("1");
        tfBloco3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 2, true));
        tfBloco3.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        tfBloco3.setEnabled(false);
        getContentPane().add(tfBloco3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 60, 60));

        tfBloco4.setEditable(false);
        tfBloco4.setBackground(new java.awt.Color(255, 255, 255));
        tfBloco4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tfBloco4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 2, true));
        tfBloco4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tfBloco4MousePressed(evt);
            }
        });
        getContentPane().add(tfBloco4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 60, 60));

        tfBloco7.setEditable(false);
        tfBloco7.setBackground(new java.awt.Color(255, 255, 255));
        tfBloco7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tfBloco7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 2, true));
        tfBloco7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tfBloco7MousePressed(evt);
            }
        });
        getContentPane().add(tfBloco7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 60, 60));

        tfBloco8.setEditable(false);
        tfBloco8.setBackground(new java.awt.Color(255, 255, 255));
        tfBloco8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tfBloco8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 2, true));
        tfBloco8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tfBloco8MousePressed(evt);
            }
        });
        getContentPane().add(tfBloco8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 60, 60));

        tfBloco9.setEditable(false);
        tfBloco9.setBackground(new java.awt.Color(255, 255, 255));
        tfBloco9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tfBloco9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 2, true));
        tfBloco9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tfBloco9MousePressed(evt);
            }
        });
        getContentPane().add(tfBloco9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 60, 60));

        tfBloco10.setEditable(false);
        tfBloco10.setBackground(new java.awt.Color(255, 255, 255));
        tfBloco10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tfBloco10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 2, true));
        tfBloco10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tfBloco10MousePressed(evt);
            }
        });
        getContentPane().add(tfBloco10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 60, 60));

        tfBloco13.setEditable(false);
        tfBloco13.setBackground(new java.awt.Color(255, 255, 255));
        tfBloco13.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tfBloco13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco13.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 2, true));
        tfBloco13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tfBloco13MousePressed(evt);
            }
        });
        getContentPane().add(tfBloco13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 60, 60));

        tfBloco14.setEditable(false);
        tfBloco14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        tfBloco14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco14.setText("3");
        tfBloco14.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 2, true));
        tfBloco14.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        tfBloco14.setEnabled(false);
        getContentPane().add(tfBloco14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 60, 60));

        tfBloco11.setEditable(false);
        tfBloco11.setBackground(new java.awt.Color(255, 255, 255));
        tfBloco11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tfBloco11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco11.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 255), 2, true));
        tfBloco11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tfBloco11MousePressed(evt);
            }
        });
        getContentPane().add(tfBloco11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 60, 60));

        tfBloco12.setEditable(false);
        tfBloco12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        tfBloco12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco12.setText("2");
        tfBloco12.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 255), 2, true));
        tfBloco12.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        tfBloco12.setEnabled(false);
        getContentPane().add(tfBloco12, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 60, 60));

        tfBloco15.setEditable(false);
        tfBloco15.setBackground(new java.awt.Color(255, 255, 255));
        tfBloco15.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tfBloco15.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco15.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 255), 2, true));
        tfBloco15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tfBloco15MousePressed(evt);
            }
        });
        getContentPane().add(tfBloco15, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 60, 60));

        tfBloco16.setEditable(false);
        tfBloco16.setBackground(new java.awt.Color(255, 255, 255));
        tfBloco16.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tfBloco16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco16.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 255), 2, true));
        tfBloco16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tfBloco16MousePressed(evt);
            }
        });
        getContentPane().add(tfBloco16, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 60, 60));

        btn1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn1.setText("1");
        btn1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 70, 70));

        btn2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn2.setText("2");
        btn2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 70, 70));

        btn3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn3.setText("3");
        btn3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        getContentPane().add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 70, 70));

        btn4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn4.setText("4");
        btn4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        getContentPane().add(btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, 70, 70));

        btnX.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnX.setText("X");
        btnX.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXActionPerformed(evt);
            }
        });
        getContentPane().add(btnX, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 110, 70));

        btnVerificar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnVerificar.setText("Verificar");
        btnVerificar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVerificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, 110, 70));

        jLabelTitulo.setFont(new java.awt.Font("Snap ITC", 3, 30)); // NOI18N
        jLabelTitulo.setText("SUDOKU 4X4");
        getContentPane().add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 270, -1));

        jLabelIcon.setFont(new java.awt.Font("Snap ITC", 0, 18)); // NOI18N
        jLabelIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sudoku/icons8-sudoku-32.png"))); // NOI18N
        jLabelIcon.setText("MÉDIO");
        getContentPane().add(jLabelIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, 120, 50));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        botaoBloco.setBotaoSelecionado(btn1);
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        botaoBloco.setBotaoSelecionado(btn2);
    }//GEN-LAST:event_btn2ActionPerformed

    private void btnXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXActionPerformed
        botaoBloco.setBotaoSelecionado(btnX);
    }//GEN-LAST:event_btnXActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        botaoBloco.setBotaoSelecionado(btn3);
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        botaoBloco.setBotaoSelecionado(btn4);
    }//GEN-LAST:event_btn4ActionPerformed

    private void btnVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificarActionPerformed
        boolean espacoEmBranco = isEspacoEmBranco();
        if (espacoEmBranco) {
            new EspacoEmBranco(this);
        } else {
            int countAcertos = 0;
            if (Integer.parseInt(tfBloco1.getText()) == 3) {
                countAcertos += 1;
            }
            if (Integer.parseInt(tfBloco2.getText()) == 2) {
                countAcertos += 1;
            }
            if (Integer.parseInt(tfBloco4.getText()) == 4) {
                countAcertos += 1;
            }
            if (Integer.parseInt(tfBloco6.getText()) == 1) {
                countAcertos += 1;
            }
            if (Integer.parseInt(tfBloco7.getText()) == 2) {
                countAcertos += 1;
            }
            if (Integer.parseInt(tfBloco8.getText()) == 3) {
                countAcertos += 1;
            }
            if (Integer.parseInt(tfBloco9.getText()) == 1) {
                countAcertos += 1;
            }
            if (Integer.parseInt(tfBloco10.getText()) == 4) {
                countAcertos += 1;
            }
            if (Integer.parseInt(tfBloco11.getText()) == 3) {
                countAcertos += 1;
            }
            if (Integer.parseInt(tfBloco13.getText()) == 2) {
                countAcertos += 1;
            }
            if (Integer.parseInt(tfBloco15.getText()) == 4) {
                countAcertos += 1;
            }
            if (Integer.parseInt(tfBloco16.getText()) == 1) {
                countAcertos += 1;
            }
            
            if (countAcertos == 12) {
                if (escolhaUsuario.isDesafio()) {
                    this.dispose();
                    new NivelDificil1("desafio").setVisible(true);
                } else if (escolhaUsuario.isIndividual()) {
                    pontuacao.vitoriaIndividual(this);
                }
            } else {
                JOptionPane.showMessageDialog(this, "QUE PENA, TENTE NOVAMENTE");
                tfBloco1.setText("");
                tfBloco2.setText("");
                tfBloco4.setText("");
                tfBloco6.setText("");
                tfBloco7.setText("");
                tfBloco8.setText("");
                tfBloco9.setText("");
                tfBloco10.setText("");
                tfBloco11.setText("");
                tfBloco13.setText("");
                tfBloco15.setText("");
                tfBloco16.setText("");
            }
        }
    }//GEN-LAST:event_btnVerificarActionPerformed

    private void tfBloco1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfBloco1MousePressed
        excecao.trataExcecao(tfBloco1, this, botaoBloco.getBotaoSelecionado());
    }//GEN-LAST:event_tfBloco1MousePressed

    private void tfBloco2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfBloco2MousePressed
        excecao.trataExcecao(tfBloco2, this, botaoBloco.getBotaoSelecionado());
    }//GEN-LAST:event_tfBloco2MousePressed

    private void tfBloco4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfBloco4MousePressed
        excecao.trataExcecao(tfBloco4, this, botaoBloco.getBotaoSelecionado());
    }//GEN-LAST:event_tfBloco4MousePressed

    private void tfBloco6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfBloco6MousePressed
        excecao.trataExcecao(tfBloco6, this, botaoBloco.getBotaoSelecionado());
    }//GEN-LAST:event_tfBloco6MousePressed

    private void tfBloco7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfBloco7MousePressed
        excecao.trataExcecao(tfBloco7, this, botaoBloco.getBotaoSelecionado());
    }//GEN-LAST:event_tfBloco7MousePressed

    private void tfBloco8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfBloco8MousePressed
        excecao.trataExcecao(tfBloco8, this, botaoBloco.getBotaoSelecionado());
    }//GEN-LAST:event_tfBloco8MousePressed

    private void tfBloco9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfBloco9MousePressed
        excecao.trataExcecao(tfBloco9, this, botaoBloco.getBotaoSelecionado());
    }//GEN-LAST:event_tfBloco9MousePressed

    private void tfBloco10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfBloco10MousePressed
        excecao.trataExcecao(tfBloco10, this, botaoBloco.getBotaoSelecionado());
    }//GEN-LAST:event_tfBloco10MousePressed

    private void tfBloco11MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfBloco11MousePressed
        excecao.trataExcecao(tfBloco11, this, botaoBloco.getBotaoSelecionado());
    }//GEN-LAST:event_tfBloco11MousePressed

    private void tfBloco13MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfBloco13MousePressed
        excecao.trataExcecao(tfBloco13, this, botaoBloco.getBotaoSelecionado());
    }//GEN-LAST:event_tfBloco13MousePressed

    private void tfBloco15MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfBloco15MousePressed
        excecao.trataExcecao(tfBloco15, this, botaoBloco.getBotaoSelecionado());
    }//GEN-LAST:event_tfBloco15MousePressed

    private void tfBloco16MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfBloco16MousePressed
        excecao.trataExcecao(tfBloco16, this, botaoBloco.getBotaoSelecionado());
    }//GEN-LAST:event_tfBloco16MousePressed
     
    private boolean isEspacoEmBranco() {
        int branco = 0;
        
        if (tfBloco1.getText().isBlank()) {
            branco = 1;
        }
        if (tfBloco2.getText().isBlank()) {
            branco = 1;
        } 
        if (tfBloco4.getText().isBlank()) {
            branco = 1;
        } 
        if (tfBloco6.getText().isBlank()) {
            branco = 1;
        } 
        if (tfBloco7.getText().isBlank()) {
            branco = 1;
        } 
        if (tfBloco8.getText().isBlank()) {
            branco = 1;
        } 
        if (tfBloco9.getText().isBlank()) {
            branco = 1;
        } 
        if (tfBloco10.getText().isBlank()) {
            branco = 1;
        } 
        if (tfBloco11.getText().isBlank()) {
            branco = 1;
        } 
        if (tfBloco13.getText().isBlank()) {
            branco = 1;
        } 
        if (tfBloco15.getText().isBlank()) {
            branco = 1;
        } 
        if (tfBloco16.getText().isBlank()) {
            branco = 1;
        } 

        if (branco == 1) {
            return true;
        } else {
            return false;
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.setLookAndFeel(
                javax.swing.UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NivelMedio1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NivelMedio1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NivelMedio1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NivelMedio1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NivelMedio1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btnVerificar;
    private javax.swing.JButton btnX;
    private javax.swing.JLabel jLabelIcon;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JTextField tfBloco1;
    private javax.swing.JTextField tfBloco10;
    private javax.swing.JTextField tfBloco11;
    private javax.swing.JTextField tfBloco12;
    private javax.swing.JTextField tfBloco13;
    private javax.swing.JTextField tfBloco14;
    private javax.swing.JTextField tfBloco15;
    private javax.swing.JTextField tfBloco16;
    private javax.swing.JTextField tfBloco2;
    private javax.swing.JTextField tfBloco3;
    private javax.swing.JTextField tfBloco4;
    private javax.swing.JTextField tfBloco5;
    private javax.swing.JTextField tfBloco6;
    private javax.swing.JTextField tfBloco7;
    private javax.swing.JTextField tfBloco8;
    private javax.swing.JTextField tfBloco9;
    // End of variables declaration//GEN-END:variables
}
