package sudoku;

import java.awt.Color;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author laura
 */
public class Sudoku9x9 extends javax.swing.JFrame {
    private int numDica;
    private int bloco12, bloco24, bloco29, bloco49, bloco63;
    private DesafioOuIndividual escolhaUsuario = new DesafioOuIndividual();
    private Vitorias pontuacao = new Vitorias();
    /**
     * Creates new form Sudoku9x9
     */
    public Sudoku9x9() {
        initComponents();
    }
    
    public Sudoku9x9(String desafioOuIndividual) {
        initComponents();
        escolhaUsuario.desafioOuIndividual(desafioOuIndividual);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfBloco1 = new javax.swing.JTextField();
        tfBloco2 = new javax.swing.JTextField();
        tfBloco3 = new javax.swing.JTextField();
        tfBloco4 = new javax.swing.JTextField();
        tfBloco5 = new javax.swing.JTextField();
        tfBloco6 = new javax.swing.JTextField();
        tfBloco7 = new javax.swing.JTextField();
        tfBloco8 = new javax.swing.JTextField();
        tfBloco9 = new javax.swing.JTextField();
        btnApagarTudo = new javax.swing.JButton();
        btnVerificar = new javax.swing.JButton();
        jLabelSubTitulo = new javax.swing.JLabel();
        tfBloco10 = new javax.swing.JTextField();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelIcon = new javax.swing.JLabel();
        tfBloco11 = new javax.swing.JTextField();
        tfBloco12 = new javax.swing.JTextField();
        tfBloco13 = new javax.swing.JTextField();
        tfBloco14 = new javax.swing.JTextField();
        tfBloco15 = new javax.swing.JTextField();
        tfBloco16 = new javax.swing.JTextField();
        tfBloco17 = new javax.swing.JTextField();
        tfBloco18 = new javax.swing.JTextField();
        tfBloco19 = new javax.swing.JTextField();
        tfBloco20 = new javax.swing.JTextField();
        tfBloco21 = new javax.swing.JTextField();
        tfBloco22 = new javax.swing.JTextField();
        tfBloco23 = new javax.swing.JTextField();
        tfBloco24 = new javax.swing.JTextField();
        tfBloco25 = new javax.swing.JTextField();
        tfBloco26 = new javax.swing.JTextField();
        tfBloco27 = new javax.swing.JTextField();
        tfBloco28 = new javax.swing.JTextField();
        tfBloco29 = new javax.swing.JTextField();
        tfBloco30 = new javax.swing.JTextField();
        tfBloco31 = new javax.swing.JTextField();
        tfBloco32 = new javax.swing.JTextField();
        tfBloco33 = new javax.swing.JTextField();
        tfBloco34 = new javax.swing.JTextField();
        tfBloco35 = new javax.swing.JTextField();
        tfBloco36 = new javax.swing.JTextField();
        tfBloco37 = new javax.swing.JTextField();
        tfBloco38 = new javax.swing.JTextField();
        tfBloco39 = new javax.swing.JTextField();
        tfBloco40 = new javax.swing.JTextField();
        tfBloco41 = new javax.swing.JTextField();
        tfBloco42 = new javax.swing.JTextField();
        tfBloco43 = new javax.swing.JTextField();
        tfBloco44 = new javax.swing.JTextField();
        tfBloco45 = new javax.swing.JTextField();
        tfBloco46 = new javax.swing.JTextField();
        tfBloco47 = new javax.swing.JTextField();
        tfBloco48 = new javax.swing.JTextField();
        tfBloco49 = new javax.swing.JTextField();
        tfBloco50 = new javax.swing.JTextField();
        tfBloco51 = new javax.swing.JTextField();
        tfBloco52 = new javax.swing.JTextField();
        tfBloco53 = new javax.swing.JTextField();
        tfBloco54 = new javax.swing.JTextField();
        tfBloco55 = new javax.swing.JTextField();
        tfBloco56 = new javax.swing.JTextField();
        tfBloco57 = new javax.swing.JTextField();
        tfBloco58 = new javax.swing.JTextField();
        tfBloco59 = new javax.swing.JTextField();
        tfBloco60 = new javax.swing.JTextField();
        tfBloco61 = new javax.swing.JTextField();
        tfBloco62 = new javax.swing.JTextField();
        tfBloco63 = new javax.swing.JTextField();
        tfBloco64 = new javax.swing.JTextField();
        tfBloco65 = new javax.swing.JTextField();
        tfBloco66 = new javax.swing.JTextField();
        tfBloco67 = new javax.swing.JTextField();
        tfBloco68 = new javax.swing.JTextField();
        tfBloco69 = new javax.swing.JTextField();
        tfBloco70 = new javax.swing.JTextField();
        tfBloco71 = new javax.swing.JTextField();
        tfBloco72 = new javax.swing.JTextField();
        tfBloco73 = new javax.swing.JTextField();
        tfBloco74 = new javax.swing.JTextField();
        tfBloco75 = new javax.swing.JTextField();
        tfBloco76 = new javax.swing.JTextField();
        jLabelTitulo2 = new javax.swing.JLabel();
        tfBloco77 = new javax.swing.JTextField();
        tfBloco78 = new javax.swing.JTextField();
        tfBloco79 = new javax.swing.JTextField();
        tfBloco80 = new javax.swing.JTextField();
        tfBloco81 = new javax.swing.JTextField();
        btnDica = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nível 3");
        setExtendedState(6);
        setMinimumSize(getPreferredSize());
        setPreferredSize(new java.awt.Dimension(1355, 695));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tfBloco1.setEditable(false);
        tfBloco1.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        tfBloco1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco1.setText("8");
        tfBloco1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 255), 2, true));
        tfBloco1.setMinimumSize(new java.awt.Dimension(60, 40));
        tfBloco1.setPreferredSize(new java.awt.Dimension(60, 40));
        getContentPane().add(tfBloco1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 71, 71));

        tfBloco2.setEditable(false);
        tfBloco2.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        tfBloco2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco2.setText("7");
        tfBloco2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 255), 2, true));
        tfBloco2.setMinimumSize(new java.awt.Dimension(60, 40));
        tfBloco2.setPreferredSize(new java.awt.Dimension(60, 40));
        getContentPane().add(tfBloco2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 71, 71));

        tfBloco3.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        tfBloco3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 255), 2, true));
        tfBloco3.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        getContentPane().add(tfBloco3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 71, 71));

        tfBloco4.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        tfBloco4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 2, true));
        getContentPane().add(tfBloco4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 71, 71));

        tfBloco5.setEditable(false);
        tfBloco5.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        tfBloco5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco5.setText("4");
        tfBloco5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 2, true));
        tfBloco5.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        getContentPane().add(tfBloco5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 71, 71));

        tfBloco6.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        tfBloco6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 2, true));
        getContentPane().add(tfBloco6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 71, 71));

        tfBloco7.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        tfBloco7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 51), 2, true));
        getContentPane().add(tfBloco7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 71, 71));

        tfBloco8.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        tfBloco8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 51), 2, true));
        tfBloco8.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        getContentPane().add(tfBloco8, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 71, 71));

        tfBloco9.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        tfBloco9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 51), 2, true));
        getContentPane().add(tfBloco9, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, 71, 71));

        btnApagarTudo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnApagarTudo.setText("Apagar tudo");
        btnApagarTudo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnApagarTudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApagarTudoActionPerformed(evt);
            }
        });
        getContentPane().add(btnApagarTudo, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 590, 160, 50));

        btnVerificar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnVerificar.setText("Verificar");
        btnVerificar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVerificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 590, 160, 50));

        jLabelSubTitulo.setFont(new java.awt.Font("Snap ITC", 2, 50)); // NOI18N
        jLabelSubTitulo.setForeground(new java.awt.Color(204, 204, 204));
        jLabelSubTitulo.setText("ULTIMATE");
        getContentPane().add(jLabelSubTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 270, 340, -1));

        tfBloco10.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        tfBloco10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 255), 2, true));
        tfBloco10.setMinimumSize(new java.awt.Dimension(60, 40));
        tfBloco10.setPreferredSize(new java.awt.Dimension(60, 40));
        getContentPane().add(tfBloco10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 71, 71));

        jLabelTitulo.setFont(new java.awt.Font("Snap ITC", 3, 130)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(204, 204, 204));
        jLabelTitulo.setText("SUDOKU");
        getContentPane().add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, -20, 690, -1));

        jLabelIcon.setBackground(new java.awt.Color(204, 204, 204));
        jLabelIcon.setForeground(new java.awt.Color(204, 204, 204));
        jLabelIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sudoku/sudoku 9x9.png"))); // NOI18N
        getContentPane().add(jLabelIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 70, 260, 270));

        tfBloco11.setEditable(false);
        tfBloco11.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        tfBloco11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco11.setText("6");
        tfBloco11.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 255), 2, true));
        tfBloco11.setMinimumSize(new java.awt.Dimension(60, 40));
        tfBloco11.setPreferredSize(new java.awt.Dimension(60, 40));
        getContentPane().add(tfBloco11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 71, 71));

        tfBloco12.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        tfBloco12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco12.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 255), 2, true));
        tfBloco12.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        getContentPane().add(tfBloco12, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 71, 71));

        tfBloco13.setEditable(false);
        tfBloco13.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        tfBloco13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco13.setText("7");
        tfBloco13.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 2, true));
        getContentPane().add(tfBloco13, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 71, 71));

        tfBloco14.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        tfBloco14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco14.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 2, true));
        tfBloco14.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        getContentPane().add(tfBloco14, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 71, 71));

        tfBloco15.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        tfBloco15.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco15.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 2, true));
        getContentPane().add(tfBloco15, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 71, 71));

        tfBloco16.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        tfBloco16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco16.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 51), 2, true));
        getContentPane().add(tfBloco16, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, 71, 71));

        tfBloco17.setEditable(false);
        tfBloco17.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        tfBloco17.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco17.setText("3");
        tfBloco17.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 51), 2, true));
        tfBloco17.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        getContentPane().add(tfBloco17, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, 71, 71));

        tfBloco18.setEditable(false);
        tfBloco18.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        tfBloco18.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco18.setText("4");
        tfBloco18.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 51), 2, true));
        getContentPane().add(tfBloco18, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 80, 71, 71));

        tfBloco19.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        tfBloco19.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco19.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 255), 2, true));
        tfBloco19.setMinimumSize(new java.awt.Dimension(60, 40));
        tfBloco19.setPreferredSize(new java.awt.Dimension(60, 40));
        getContentPane().add(tfBloco19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 71, 71));

        tfBloco20.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        tfBloco20.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco20.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 255), 2, true));
        tfBloco20.setMinimumSize(new java.awt.Dimension(60, 40));
        tfBloco20.setPreferredSize(new java.awt.Dimension(60, 40));
        getContentPane().add(tfBloco20, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 71, 71));

        tfBloco21.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        tfBloco21.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco21.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 255), 2, true));
        tfBloco21.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        getContentPane().add(tfBloco21, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 71, 71));

        tfBloco22.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        tfBloco22.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco22.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 2, true));
        getContentPane().add(tfBloco22, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 71, 71));

        tfBloco23.setEditable(false);
        tfBloco23.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        tfBloco23.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco23.setText("6");
        tfBloco23.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 2, true));
        tfBloco23.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        getContentPane().add(tfBloco23, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 71, 71));

        tfBloco24.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        tfBloco24.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco24.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 2, true));
        getContentPane().add(tfBloco24, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 71, 71));

        tfBloco25.setEditable(false);
        tfBloco25.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        tfBloco25.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco25.setText("5");
        tfBloco25.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 51), 2, true));
        getContentPane().add(tfBloco25, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, 71, 71));

        tfBloco26.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        tfBloco26.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco26.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 51), 2, true));
        tfBloco26.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        getContentPane().add(tfBloco26, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, 71, 71));

        tfBloco27.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        tfBloco27.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco27.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 51), 2, true));
        getContentPane().add(tfBloco27, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 150, 71, 71));

        tfBloco28.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        tfBloco28.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco28.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        tfBloco28.setMinimumSize(new java.awt.Dimension(60, 40));
        tfBloco28.setPreferredSize(new java.awt.Dimension(60, 40));
        getContentPane().add(tfBloco28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 71, 71));

        tfBloco29.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        tfBloco29.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco29.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        tfBloco29.setMinimumSize(new java.awt.Dimension(60, 40));
        tfBloco29.setPreferredSize(new java.awt.Dimension(60, 40));
        getContentPane().add(tfBloco29, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 71, 71));

        tfBloco30.setEditable(false);
        tfBloco30.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        tfBloco30.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco30.setText("2");
        tfBloco30.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        tfBloco30.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        getContentPane().add(tfBloco30, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 71, 71));

        tfBloco31.setEditable(false);
        tfBloco31.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        tfBloco31.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco31.setText("4");
        tfBloco31.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 153), 2, true));
        getContentPane().add(tfBloco31, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 71, 71));

        tfBloco32.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        tfBloco32.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco32.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 153), 2, true));
        tfBloco32.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        getContentPane().add(tfBloco32, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 71, 71));

        tfBloco33.setEditable(false);
        tfBloco33.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        tfBloco33.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco33.setText("1");
        tfBloco33.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 153), 2, true));
        getContentPane().add(tfBloco33, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, 71, 71));

        tfBloco34.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        tfBloco34.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco34.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 51), 2, true));
        getContentPane().add(tfBloco34, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, 71, 71));

        tfBloco35.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        tfBloco35.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco35.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 51), 2, true));
        tfBloco35.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        getContentPane().add(tfBloco35, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 220, 71, 71));

        tfBloco36.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        tfBloco36.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco36.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 51), 2, true));
        getContentPane().add(tfBloco36, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 220, 71, 71));

        tfBloco37.setEditable(false);
        tfBloco37.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        tfBloco37.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco37.setText("7");
        tfBloco37.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        tfBloco37.setMinimumSize(new java.awt.Dimension(60, 40));
        tfBloco37.setPreferredSize(new java.awt.Dimension(60, 40));
        getContentPane().add(tfBloco37, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 71, 71));

        tfBloco38.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        tfBloco38.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco38.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        tfBloco38.setMinimumSize(new java.awt.Dimension(60, 40));
        tfBloco38.setPreferredSize(new java.awt.Dimension(60, 40));
        getContentPane().add(tfBloco38, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 71, 71));

        tfBloco39.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        tfBloco39.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco39.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        tfBloco39.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        getContentPane().add(tfBloco39, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 71, 71));

        tfBloco40.setEditable(false);
        tfBloco40.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        tfBloco40.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco40.setText("5");
        tfBloco40.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 153), 2, true));
        getContentPane().add(tfBloco40, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 71, 71));

        tfBloco41.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        tfBloco41.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco41.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 153), 2, true));
        tfBloco41.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        getContentPane().add(tfBloco41, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, 71, 71));

        tfBloco42.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        tfBloco42.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco42.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 153), 2, true));
        getContentPane().add(tfBloco42, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, 71, 71));

        tfBloco43.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        tfBloco43.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco43.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 51), 2, true));
        getContentPane().add(tfBloco43, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, 71, 71));

        tfBloco44.setEditable(false);
        tfBloco44.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        tfBloco44.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco44.setText("4");
        tfBloco44.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 51), 2, true));
        tfBloco44.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        getContentPane().add(tfBloco44, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 290, 71, 71));

        tfBloco45.setEditable(false);
        tfBloco45.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        tfBloco45.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco45.setText("2");
        tfBloco45.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 51), 2, true));
        getContentPane().add(tfBloco45, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 290, 71, 71));

        tfBloco46.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        tfBloco46.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco46.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        tfBloco46.setMinimumSize(new java.awt.Dimension(60, 40));
        tfBloco46.setPreferredSize(new java.awt.Dimension(60, 40));
        getContentPane().add(tfBloco46, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 71, 71));

        tfBloco47.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        tfBloco47.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco47.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        tfBloco47.setMinimumSize(new java.awt.Dimension(60, 40));
        tfBloco47.setPreferredSize(new java.awt.Dimension(60, 40));
        getContentPane().add(tfBloco47, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 71, 71));

        tfBloco48.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        tfBloco48.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco48.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        tfBloco48.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        getContentPane().add(tfBloco48, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 71, 71));

        tfBloco49.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        tfBloco49.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco49.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 153), 2, true));
        getContentPane().add(tfBloco49, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 71, 71));

        tfBloco50.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        tfBloco50.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco50.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 153), 2, true));
        tfBloco50.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        getContentPane().add(tfBloco50, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, 71, 71));

        tfBloco51.setEditable(false);
        tfBloco51.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        tfBloco51.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco51.setText("8");
        tfBloco51.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 153), 2, true));
        getContentPane().add(tfBloco51, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, 71, 71));

        tfBloco52.setEditable(false);
        tfBloco52.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        tfBloco52.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco52.setText("1");
        tfBloco52.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 51), 2, true));
        getContentPane().add(tfBloco52, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 360, 71, 71));

        tfBloco53.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        tfBloco53.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco53.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 51), 2, true));
        tfBloco53.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        getContentPane().add(tfBloco53, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 360, 71, 71));

        tfBloco54.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        tfBloco54.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco54.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 51), 2, true));
        getContentPane().add(tfBloco54, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 360, 71, 71));

        tfBloco55.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        tfBloco55.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco55.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 0), 2, true));
        tfBloco55.setMinimumSize(new java.awt.Dimension(60, 40));
        tfBloco55.setPreferredSize(new java.awt.Dimension(60, 40));
        getContentPane().add(tfBloco55, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 71, 71));

        tfBloco56.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        tfBloco56.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco56.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 0), 2, true));
        tfBloco56.setMinimumSize(new java.awt.Dimension(60, 40));
        tfBloco56.setPreferredSize(new java.awt.Dimension(60, 40));
        getContentPane().add(tfBloco56, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, 71, 71));

        tfBloco57.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        tfBloco57.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco57.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 0), 2, true));
        tfBloco57.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        getContentPane().add(tfBloco57, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, 71, 71));

        tfBloco58.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        tfBloco58.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco58.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true));
        getContentPane().add(tfBloco58, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 430, 71, 71));

        tfBloco59.setEditable(false);
        tfBloco59.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        tfBloco59.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco59.setText("1");
        tfBloco59.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true));
        tfBloco59.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        getContentPane().add(tfBloco59, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 430, 71, 71));

        tfBloco60.setEditable(false);
        tfBloco60.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        tfBloco60.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco60.setText("4");
        tfBloco60.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true));
        getContentPane().add(tfBloco60, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 430, 71, 71));

        tfBloco61.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        tfBloco61.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco61.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 2, true));
        getContentPane().add(tfBloco61, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 430, 71, 71));

        tfBloco62.setEditable(false);
        tfBloco62.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        tfBloco62.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco62.setText("5");
        tfBloco62.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 2, true));
        tfBloco62.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        getContentPane().add(tfBloco62, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 430, 71, 71));

        tfBloco63.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        tfBloco63.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco63.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 2, true));
        getContentPane().add(tfBloco63, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 430, 71, 71));

        tfBloco64.setEditable(false);
        tfBloco64.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        tfBloco64.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco64.setText("5");
        tfBloco64.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 0), 2, true));
        tfBloco64.setMinimumSize(new java.awt.Dimension(60, 40));
        tfBloco64.setPreferredSize(new java.awt.Dimension(60, 40));
        getContentPane().add(tfBloco64, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 71, 71));

        tfBloco65.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        tfBloco65.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco65.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 0), 2, true));
        tfBloco65.setMinimumSize(new java.awt.Dimension(60, 40));
        tfBloco65.setPreferredSize(new java.awt.Dimension(60, 40));
        getContentPane().add(tfBloco65, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 500, 71, 71));

        tfBloco66.setEditable(false);
        tfBloco66.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        tfBloco66.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco66.setText("9");
        tfBloco66.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 0), 2, true));
        tfBloco66.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        getContentPane().add(tfBloco66, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 500, 71, 71));

        tfBloco67.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        tfBloco67.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco67.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true));
        getContentPane().add(tfBloco67, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 500, 71, 71));

        tfBloco68.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        tfBloco68.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco68.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true));
        tfBloco68.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        getContentPane().add(tfBloco68, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 500, 71, 71));

        tfBloco69.setEditable(false);
        tfBloco69.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        tfBloco69.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco69.setText("3");
        tfBloco69.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true));
        getContentPane().add(tfBloco69, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 500, 71, 71));

        tfBloco70.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        tfBloco70.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco70.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 2, true));
        getContentPane().add(tfBloco70, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 500, 71, 71));

        tfBloco71.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        tfBloco71.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco71.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 2, true));
        tfBloco71.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        getContentPane().add(tfBloco71, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 500, 71, 71));

        tfBloco72.setEditable(false);
        tfBloco72.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        tfBloco72.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco72.setText("1");
        tfBloco72.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 2, true));
        getContentPane().add(tfBloco72, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 500, 71, 71));

        tfBloco73.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        tfBloco73.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco73.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 0), 2, true));
        tfBloco73.setMinimumSize(new java.awt.Dimension(60, 40));
        tfBloco73.setPreferredSize(new java.awt.Dimension(60, 40));
        getContentPane().add(tfBloco73, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 570, 71, 71));

        tfBloco74.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        tfBloco74.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco74.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 0), 2, true));
        tfBloco74.setMinimumSize(new java.awt.Dimension(60, 40));
        tfBloco74.setPreferredSize(new java.awt.Dimension(60, 40));
        getContentPane().add(tfBloco74, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 570, 71, 71));

        tfBloco75.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        tfBloco75.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco75.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 0), 2, true));
        tfBloco75.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        getContentPane().add(tfBloco75, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 570, 71, 71));

        tfBloco76.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        tfBloco76.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco76.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true));
        getContentPane().add(tfBloco76, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 570, 71, 71));

        jLabelTitulo2.setFont(new java.awt.Font("Snap ITC", 1, 160)); // NOI18N
        jLabelTitulo2.setText("9x9");
        getContentPane().add(jLabelTitulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 60, -1, -1));

        tfBloco77.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        tfBloco77.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco77.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true));
        tfBloco77.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        getContentPane().add(tfBloco77, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 570, 71, 71));

        tfBloco78.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        tfBloco78.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco78.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true));
        getContentPane().add(tfBloco78, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 570, 71, 71));

        tfBloco79.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        tfBloco79.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco79.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 2, true));
        getContentPane().add(tfBloco79, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 570, 71, 71));

        tfBloco80.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        tfBloco80.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco80.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 2, true));
        tfBloco80.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        getContentPane().add(tfBloco80, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 570, 71, 71));

        tfBloco81.setEditable(false);
        tfBloco81.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        tfBloco81.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco81.setText("6");
        tfBloco81.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 2, true));
        getContentPane().add(tfBloco81, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 570, 71, 71));

        btnDica.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDica.setText("Dica");
        btnDica.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDicaActionPerformed(evt);
            }
        });
        getContentPane().add(btnDica, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 590, 160, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnApagarTudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagarTudoActionPerformed
        apagarBlocos();
    }//GEN-LAST:event_btnApagarTudoActionPerformed

    private void btnVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificarActionPerformed
        boolean espacoEmBranco = isEspacoEmBranco();
        
        if (espacoEmBranco) {
            new EspacoEmBranco(this);
        } else {
            int countAcertos = 0;
            
            if (Integer.parseInt(tfBloco3.getText()) == 5) {
                countAcertos += 1;
            }
            if (Integer.parseInt(tfBloco4.getText()) == 3) {
                countAcertos += 1;
            }
            if (Integer.parseInt(tfBloco6.getText()) == 2) {
                countAcertos += 1;
            }
            if (Integer.parseInt(tfBloco7.getText()) == 6) {
                countAcertos += 1;
            }
            if (Integer.parseInt(tfBloco8.getText()) == 1) {
                countAcertos += 1;
            }
            if (Integer.parseInt(tfBloco9.getText()) == 9) {
                countAcertos += 1;
            }
            if (Integer.parseInt(tfBloco10.getText()) == 9) {
                countAcertos += 1;
            }
            if (Integer.parseInt(tfBloco12.getText()) == 1) {
                countAcertos += 1;
            }
            if (Integer.parseInt(tfBloco14.getText()) == 8) {
                countAcertos += 1;
            }
            if (Integer.parseInt(tfBloco15.getText()) == 5) {
                countAcertos += 1;
            }
            if (Integer.parseInt(tfBloco16.getText()) == 2) {
                countAcertos += 1;
            }
            if (Integer.parseInt(tfBloco19.getText()) == 2) {
                countAcertos += 1;
            }
            if (Integer.parseInt(tfBloco20.getText()) == 3) {
                countAcertos += 1;
            }
            if (Integer.parseInt(tfBloco21.getText()) == 4) {
                countAcertos += 1;
            }
            if (Integer.parseInt(tfBloco22.getText()) == 1) {
                countAcertos += 1;
            }
            if (Integer.parseInt(tfBloco24.getText()) == 9) {
                countAcertos += 1;
            }
            if (Integer.parseInt(tfBloco26.getText()) == 7) {
                countAcertos += 1;
            }
            if (Integer.parseInt(tfBloco27.getText()) == 8) {
                countAcertos += 1;
            }
            if (Integer.parseInt(tfBloco28.getText()) == 3) {
                countAcertos += 1;
            }
            if (Integer.parseInt(tfBloco29.getText()) == 9) {
                countAcertos += 1;
            }
            if (Integer.parseInt(tfBloco32.getText()) == 7) {
                countAcertos += 1;
            }
            if (Integer.parseInt(tfBloco34.getText()) == 8) {
                countAcertos += 1;
            }
            if (Integer.parseInt(tfBloco35.getText()) == 6) {
                countAcertos += 1;
            }
            if (Integer.parseInt(tfBloco36.getText()) == 5) {
                countAcertos += 1;
            }
            if (Integer.parseInt(tfBloco38.getText()) == 1) {
                countAcertos += 1;
            }
            if (Integer.parseInt(tfBloco39.getText()) == 8) {
                countAcertos += 1;
            }
            if (Integer.parseInt(tfBloco41.getText()) == 9) {
                countAcertos += 1;
            }
            if (Integer.parseInt(tfBloco42.getText()) == 6) {
                countAcertos += 1;
            }
            if (Integer.parseInt(tfBloco43.getText()) == 3) {
                countAcertos += 1;
            }
            if (Integer.parseInt(tfBloco46.getText()) == 4) {
                countAcertos += 1;
            }
            if (Integer.parseInt(tfBloco47.getText()) == 5) {
                countAcertos += 1;
            }
            if (Integer.parseInt(tfBloco48.getText()) == 6) {
                countAcertos += 1;
            }
            if (Integer.parseInt(tfBloco49.getText()) == 2) {
                countAcertos += 1;
            }
            if (Integer.parseInt(tfBloco50.getText()) == 3) {
                countAcertos += 1;
            }
            if (Integer.parseInt(tfBloco53.getText()) == 9) {
                countAcertos += 1;
            }
            if (Integer.parseInt(tfBloco54.getText()) == 7) {
                countAcertos += 1;
            }
            if (Integer.parseInt(tfBloco55.getText()) == 6) {
                countAcertos += 1;
            }
            if (Integer.parseInt(tfBloco56.getText()) == 2) {
                countAcertos += 1;
            }
            if (Integer.parseInt(tfBloco57.getText()) == 7) {
                countAcertos += 1;
            }
            if (Integer.parseInt(tfBloco58.getText()) == 8) {
                countAcertos += 1;
            }
            if (Integer.parseInt(tfBloco61.getText()) == 9) {
                countAcertos += 1;
            }
            if (Integer.parseInt(tfBloco63.getText()) == 3) {
                countAcertos += 1;
            }
            if (Integer.parseInt(tfBloco65.getText()) == 4) {
                countAcertos += 1;
            }
            if (Integer.parseInt(tfBloco67.getText()) == 6) {
                countAcertos += 1;
            }
            if (Integer.parseInt(tfBloco68.getText()) == 2) {
                countAcertos += 1;
            }
            if (Integer.parseInt(tfBloco70.getText()) == 7) {
                countAcertos += 1;
            }
            if (Integer.parseInt(tfBloco71.getText()) == 8) {
                countAcertos += 1;
            }
            if (Integer.parseInt(tfBloco73.getText()) == 1) {
                countAcertos += 1;
            }
            if (Integer.parseInt(tfBloco74.getText()) == 8) {
                countAcertos += 1;
            }
            if (Integer.parseInt(tfBloco75.getText()) == 3) {
                countAcertos += 1;
            }
            if (Integer.parseInt(tfBloco76.getText()) == 9) {
                countAcertos += 1;
            }
            if (Integer.parseInt(tfBloco77.getText()) == 5) {
                countAcertos += 1;
            }
            if (Integer.parseInt(tfBloco78.getText()) == 7) {
                countAcertos += 1;
            }
            if (Integer.parseInt(tfBloco79.getText()) == 4) {
                countAcertos += 1;
            }
            if (Integer.parseInt(tfBloco80.getText()) == 2) {
                countAcertos += 1;
            }
            
            if (countAcertos == 55) {
                if (escolhaUsuario.isDesafio()) {
                    JOptionPane.showMessageDialog(this, "VOCÊ CONSEGUIU VENCER"
                            + " TODAS AS ETAPAS DO DESAFIO! PARABÉNS!!!!");
                    JOptionPane.showMessageDialog(this, "Obrigada por jogar!"
                            + "\nAté a próxima!");
                    this.dispose();
                } else if (escolhaUsuario.isIndividual()) {
                    pontuacao.vitoriaIndividual(this);
                }
            } else {
                JOptionPane.showMessageDialog(this, "QUE PENA, TENTE NOVAMENTE");
                apagarBlocos();
            }
        }
    }//GEN-LAST:event_btnVerificarActionPerformed

    private void btnDicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDicaActionPerformed
        if ((tfBloco12.getText().isBlank() || tfBloco12.getText() != "1")
                && numDica == 0) {
            tfBloco12.setEditable(false);
            tfBloco12.setForeground(Color.RED);
            tfBloco12.setText("1");
            numDica = 1;
            bloco12 = 1;
        } else if ((tfBloco24.getText().isBlank() || tfBloco24.getText() != "9")
                && numDica == 1) {
            tfBloco24.setEditable(false);
            tfBloco24.setForeground(Color.RED);
            tfBloco24.setText("9");
            numDica = 2;
            bloco24 = 1;
        } else if ((tfBloco29.getText().isBlank() || tfBloco29.getText() != "9")
                && numDica == 2) {
            tfBloco29.setEditable(false);
            tfBloco29.setForeground(Color.RED);
            tfBloco29.setText("9");
            numDica = 3;
            bloco29 = 1;
        } else if ((tfBloco49.getText().isBlank() || tfBloco49.getText() != "2")
                && numDica == 3) {
            tfBloco49.setEditable(false);
            tfBloco49.setForeground(Color.RED);
            tfBloco49.setText("2");
            numDica = 4;
            bloco49 = 1;
        } else if ((tfBloco63.getText().isBlank() || tfBloco63.getText() != "3")
                && numDica == 4) {
            tfBloco63.setEditable(false);
            tfBloco63.setForeground(Color.RED);
            tfBloco63.setText("3");
            numDica = 5;
            bloco63 = 1;
        } else if (numDica == 5) {
            JOptionPane.showMessageDialog(this, "Acabaram as dicas", "Alerta", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnDicaActionPerformed

    private boolean isEspacoEmBranco() {
        int branco = 0;

        if (tfBloco3.getText().isBlank()) {
            branco = 1;
        } 
        if (tfBloco4.getText().isBlank()) {
            branco = 1;
        } 
        if (tfBloco6.getText().isBlank()) {
            branco = 1;
        } 
        if (tfBloco7.getText().isBlank()) {
            branco = 1;
        } 
        if (tfBloco8.getText().isBlank()) {
            branco = 1;
        } 
        if (tfBloco9.getText().isBlank()) {
            branco = 1;
        } 
        if (tfBloco10.getText().isBlank()) {
            branco = 1;
        } 
        if (tfBloco14.getText().isBlank()) {
            branco = 1;
        } 
        if (tfBloco15.getText().isBlank()) {
            branco = 1;
        } 
        if (tfBloco16.getText().isBlank()) {
            branco = 1;
        }
        if (tfBloco19.getText().isBlank()) {
            branco = 1;
        }
        if (tfBloco20.getText().isBlank()) {
            branco = 1;
        }
        if (tfBloco21.getText().isBlank()) {
            branco = 1;
        }
        if (tfBloco22.getText().isBlank()) {
            branco = 1;
        }
        if (tfBloco26.getText().isBlank()) {
            branco = 1;
        }
        if (tfBloco27.getText().isBlank()) {
            branco = 1;
        }
        if (tfBloco28.getText().isBlank()) {
            branco = 1;
        }
        if (tfBloco32.getText().isBlank()) {
            branco = 1;
        }
        if (tfBloco34.getText().isBlank()) {
            branco = 1;
        }
        if (tfBloco35.getText().isBlank()) {
            branco = 1;
        }
        if (tfBloco36.getText().isBlank()) {
            branco = 1;
        }
        if (tfBloco38.getText().isBlank()) {
            branco = 1;
        }
        if (tfBloco39.getText().isBlank()) {
            branco = 1;
        }
        if (tfBloco41.getText().isBlank()) {
            branco = 1;
        }
        if (tfBloco42.getText().isBlank()) {
            branco = 1;
        }
        if (tfBloco43.getText().isBlank()) {
            branco = 1;
        }
        if (tfBloco46.getText().isBlank()) {
            branco = 1;
        }
        if (tfBloco47.getText().isBlank()) {
            branco = 1;
        }
        if (tfBloco48.getText().isBlank()) {
            branco = 1;
        }
        if (tfBloco50.getText().isBlank()) {
            branco = 1;
        }
        if (tfBloco53.getText().isBlank()) {
            branco = 1;
        }
        if (tfBloco54.getText().isBlank()) {
            branco = 1;
        }
        if (tfBloco55.getText().isBlank()) {
            branco = 1;
        }
        if (tfBloco56.getText().isBlank()) {
            branco = 1;
        }
        if (tfBloco57.getText().isBlank()) {
            branco = 1;
        }
        if (tfBloco58.getText().isBlank()) {
            branco = 1;
        }
        if (tfBloco61.getText().isBlank()) {
            branco = 1;
        }
        if (tfBloco65.getText().isBlank()) {
            branco = 1;
        }
        if (tfBloco67.getText().isBlank()) {
            branco = 1;
        }
        if (tfBloco68.getText().isBlank()) {
            branco = 1;
        }
        if (tfBloco70.getText().isBlank()) {
            branco = 1;
        }
        if (tfBloco71.getText().isBlank()) {
            branco = 1;
        }
        if (tfBloco73.getText().isBlank()) {
            branco = 1;
        }
        if (tfBloco74.getText().isBlank()) {
            branco = 1;
        }
        if (tfBloco75.getText().isBlank()) {
            branco = 1;
        }
        if (tfBloco76.getText().isBlank()) {
            branco = 1;
        }
        if (tfBloco77.getText().isBlank()) {
            branco = 1;
        }
        if (tfBloco78.getText().isBlank()) {
            branco = 1;
        }
        if (tfBloco79.getText().isBlank()) {
            branco = 1;
        }
        if (tfBloco80.getText().isBlank()) {
            branco = 1;
        }
        
        if (branco == 1) {
            return true;
        } else {
            return false;
        }
    }
        
    private void apagarBlocos() {
        if (bloco12 == 0) {
            tfBloco12.setText("");
        }
        if (bloco24 == 0) {
            tfBloco24.setText("");
        }
        if (bloco29 == 0) {
            tfBloco29.setText("");
        }
        if (bloco49 == 0) {
            tfBloco49.setText("");
        }
        if (bloco63 == 0) {
            tfBloco63.setText("");
        }
        
        tfBloco3.setText("");
        tfBloco4.setText("");
        tfBloco6.setText("");
        tfBloco7.setText("");
        tfBloco8.setText("");
        tfBloco9.setText("");
        tfBloco10.setText("");
        tfBloco14.setText("");
        tfBloco15.setText("");
        tfBloco16.setText("");
        tfBloco19.setText("");
        tfBloco20.setText("");
        tfBloco21.setText("");
        tfBloco22.setText("");
        tfBloco26.setText("");
        tfBloco27.setText("");
        tfBloco28.setText("");
        tfBloco32.setText("");
        tfBloco34.setText("");
        tfBloco35.setText("");
        tfBloco36.setText("");
        tfBloco38.setText("");
        tfBloco39.setText("");
        tfBloco41.setText("");
        tfBloco42.setText("");
        tfBloco43.setText("");
        tfBloco46.setText("");
        tfBloco47.setText("");
        tfBloco48.setText("");
        tfBloco50.setText("");
        tfBloco53.setText("");
        tfBloco54.setText("");
        tfBloco55.setText("");
        tfBloco56.setText("");
        tfBloco57.setText("");
        tfBloco58.setText("");
        tfBloco61.setText("");
        tfBloco65.setText("");
        tfBloco67.setText("");
        tfBloco68.setText("");
        tfBloco70.setText("");
        tfBloco71.setText("");
        tfBloco73.setText("");
        tfBloco74.setText("");
        tfBloco75.setText("");
        tfBloco76.setText("");
        tfBloco77.setText("");
        tfBloco78.setText("");
        tfBloco79.setText("");
        tfBloco80.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.setLookAndFeel(
                javax.swing.UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sudoku9x9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sudoku9x9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sudoku9x9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sudoku9x9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sudoku9x9().setVisible(true);
                new Sudoku9x9().setExtendedState(MAXIMIZED_BOTH);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApagarTudo;
    private javax.swing.JButton btnDica;
    private javax.swing.JButton btnVerificar;
    private javax.swing.JLabel jLabelIcon;
    private javax.swing.JLabel jLabelSubTitulo;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelTitulo2;
    private javax.swing.JTextField tfBloco1;
    private javax.swing.JTextField tfBloco10;
    private javax.swing.JTextField tfBloco11;
    private javax.swing.JTextField tfBloco12;
    private javax.swing.JTextField tfBloco13;
    private javax.swing.JTextField tfBloco14;
    private javax.swing.JTextField tfBloco15;
    private javax.swing.JTextField tfBloco16;
    private javax.swing.JTextField tfBloco17;
    private javax.swing.JTextField tfBloco18;
    private javax.swing.JTextField tfBloco19;
    private javax.swing.JTextField tfBloco2;
    private javax.swing.JTextField tfBloco20;
    private javax.swing.JTextField tfBloco21;
    private javax.swing.JTextField tfBloco22;
    private javax.swing.JTextField tfBloco23;
    private javax.swing.JTextField tfBloco24;
    private javax.swing.JTextField tfBloco25;
    private javax.swing.JTextField tfBloco26;
    private javax.swing.JTextField tfBloco27;
    private javax.swing.JTextField tfBloco28;
    private javax.swing.JTextField tfBloco29;
    private javax.swing.JTextField tfBloco3;
    private javax.swing.JTextField tfBloco30;
    private javax.swing.JTextField tfBloco31;
    private javax.swing.JTextField tfBloco32;
    private javax.swing.JTextField tfBloco33;
    private javax.swing.JTextField tfBloco34;
    private javax.swing.JTextField tfBloco35;
    private javax.swing.JTextField tfBloco36;
    private javax.swing.JTextField tfBloco37;
    private javax.swing.JTextField tfBloco38;
    private javax.swing.JTextField tfBloco39;
    private javax.swing.JTextField tfBloco4;
    private javax.swing.JTextField tfBloco40;
    private javax.swing.JTextField tfBloco41;
    private javax.swing.JTextField tfBloco42;
    private javax.swing.JTextField tfBloco43;
    private javax.swing.JTextField tfBloco44;
    private javax.swing.JTextField tfBloco45;
    private javax.swing.JTextField tfBloco46;
    private javax.swing.JTextField tfBloco47;
    private javax.swing.JTextField tfBloco48;
    private javax.swing.JTextField tfBloco49;
    private javax.swing.JTextField tfBloco5;
    private javax.swing.JTextField tfBloco50;
    private javax.swing.JTextField tfBloco51;
    private javax.swing.JTextField tfBloco52;
    private javax.swing.JTextField tfBloco53;
    private javax.swing.JTextField tfBloco54;
    private javax.swing.JTextField tfBloco55;
    private javax.swing.JTextField tfBloco56;
    private javax.swing.JTextField tfBloco57;
    private javax.swing.JTextField tfBloco58;
    private javax.swing.JTextField tfBloco59;
    private javax.swing.JTextField tfBloco6;
    private javax.swing.JTextField tfBloco60;
    private javax.swing.JTextField tfBloco61;
    private javax.swing.JTextField tfBloco62;
    private javax.swing.JTextField tfBloco63;
    private javax.swing.JTextField tfBloco64;
    private javax.swing.JTextField tfBloco65;
    private javax.swing.JTextField tfBloco66;
    private javax.swing.JTextField tfBloco67;
    private javax.swing.JTextField tfBloco68;
    private javax.swing.JTextField tfBloco69;
    private javax.swing.JTextField tfBloco7;
    private javax.swing.JTextField tfBloco70;
    private javax.swing.JTextField tfBloco71;
    private javax.swing.JTextField tfBloco72;
    private javax.swing.JTextField tfBloco73;
    private javax.swing.JTextField tfBloco74;
    private javax.swing.JTextField tfBloco75;
    private javax.swing.JTextField tfBloco76;
    private javax.swing.JTextField tfBloco77;
    private javax.swing.JTextField tfBloco78;
    private javax.swing.JTextField tfBloco79;
    private javax.swing.JTextField tfBloco8;
    private javax.swing.JTextField tfBloco80;
    private javax.swing.JTextField tfBloco81;
    private javax.swing.JTextField tfBloco9;
    // End of variables declaration//GEN-END:variables
}
