package sudoku;

import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author laura
 */
public class Sudoku6x6 extends javax.swing.JFrame {
    private DesafioOuIndividual escolhaUsuario = new DesafioOuIndividual();
    private Vitorias pontuacao = new Vitorias();
    /**
     * Creates new form Sudoku6x6
     * @param desafioOuIndividual
     */
    public Sudoku6x6(String desafioOuIndividual) {
        initComponents();
        escolhaUsuario.desafioOuIndividual(desafioOuIndividual);
    }
    
    public Sudoku6x6() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfBloco1 = new javax.swing.JTextField();
        tfBloco2 = new javax.swing.JTextField();
        tfBloco7 = new javax.swing.JTextField();
        tfBloco8 = new javax.swing.JTextField();
        tfBloco3 = new javax.swing.JTextField();
        tfBloco4 = new javax.swing.JTextField();
        tfBloco9 = new javax.swing.JTextField();
        tfBloco10 = new javax.swing.JTextField();
        tfBloco13 = new javax.swing.JTextField();
        tfBloco14 = new javax.swing.JTextField();
        tfBloco19 = new javax.swing.JTextField();
        tfBloco20 = new javax.swing.JTextField();
        tfBloco15 = new javax.swing.JTextField();
        tfBloco16 = new javax.swing.JTextField();
        tfBloco21 = new javax.swing.JTextField();
        tfBloco22 = new javax.swing.JTextField();
        tfBloco5 = new javax.swing.JTextField();
        tfBloco6 = new javax.swing.JTextField();
        tfBloco11 = new javax.swing.JTextField();
        tfBloco12 = new javax.swing.JTextField();
        tfBloco17 = new javax.swing.JTextField();
        tfBloco18 = new javax.swing.JTextField();
        tfBloco23 = new javax.swing.JTextField();
        tfBloco24 = new javax.swing.JTextField();
        tfBloco25 = new javax.swing.JTextField();
        tfBloco26 = new javax.swing.JTextField();
        tfBloco31 = new javax.swing.JTextField();
        tfBloco32 = new javax.swing.JTextField();
        tfBloco27 = new javax.swing.JTextField();
        tfBloco28 = new javax.swing.JTextField();
        tfBloco33 = new javax.swing.JTextField();
        tfBloco34 = new javax.swing.JTextField();
        tfBloco29 = new javax.swing.JTextField();
        tfBloco30 = new javax.swing.JTextField();
        tfBloco35 = new javax.swing.JTextField();
        tfBloco36 = new javax.swing.JTextField();
        btnApagarTudo = new javax.swing.JButton();
        btnVerificar = new javax.swing.JButton();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelSubTitulo = new javax.swing.JLabel();
        jLabelTitulo2 = new javax.swing.JLabel();
        jLabelIcon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nível 2");
        setMinimumSize(getPreferredSize());
        setPreferredSize(new java.awt.Dimension(790, 420));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tfBloco1.setEditable(false);
        tfBloco1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        tfBloco1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco1.setText("2");
        tfBloco1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 255), 2, true));
        tfBloco1.setMinimumSize(new java.awt.Dimension(60, 40));
        tfBloco1.setPreferredSize(new java.awt.Dimension(60, 40));
        getContentPane().add(tfBloco1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, 60));

        tfBloco2.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        tfBloco2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 255), 2, true));
        tfBloco2.setMinimumSize(new java.awt.Dimension(60, 40));
        tfBloco2.setPreferredSize(new java.awt.Dimension(60, 40));
        getContentPane().add(tfBloco2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 60, 60));

        tfBloco7.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        tfBloco7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 255), 2, true));
        tfBloco7.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        tfBloco7.setMinimumSize(new java.awt.Dimension(60, 40));
        getContentPane().add(tfBloco7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 60, 60));

        tfBloco8.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        tfBloco8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 255), 2, true));
        getContentPane().add(tfBloco8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 60, 60));

        tfBloco3.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        tfBloco3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 255), 2, true));
        tfBloco3.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        getContentPane().add(tfBloco3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 60, 60));

        tfBloco4.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        tfBloco4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 51), 2, true));
        getContentPane().add(tfBloco4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 60, 60));

        tfBloco9.setEditable(false);
        tfBloco9.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        tfBloco9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco9.setText("4");
        tfBloco9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 255), 2, true));
        tfBloco9.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        getContentPane().add(tfBloco9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 60, 60));

        tfBloco10.setEditable(false);
        tfBloco10.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        tfBloco10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco10.setText("3");
        tfBloco10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 51), 2, true));
        getContentPane().add(tfBloco10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 60, 60));

        tfBloco13.setEditable(false);
        tfBloco13.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        tfBloco13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco13.setText("5");
        tfBloco13.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 51), 2, true));
        getContentPane().add(tfBloco13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 60, 60));

        tfBloco14.setEditable(false);
        tfBloco14.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        tfBloco14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco14.setText("4");
        tfBloco14.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 51), 2, true));
        tfBloco14.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        getContentPane().add(tfBloco14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 60, 60));

        tfBloco19.setEditable(false);
        tfBloco19.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        tfBloco19.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco19.setText("3");
        tfBloco19.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 51), 2, true));
        getContentPane().add(tfBloco19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 60, 60));

        tfBloco20.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        tfBloco20.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco20.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 51), 2, true));
        tfBloco20.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        getContentPane().add(tfBloco20, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 60, 60));

        tfBloco15.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        tfBloco15.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco15.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 51), 2, true));
        getContentPane().add(tfBloco15, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 60, 60));

        tfBloco16.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        tfBloco16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco16.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 2, true));
        tfBloco16.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        getContentPane().add(tfBloco16, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 60, 60));

        tfBloco21.setEditable(false);
        tfBloco21.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        tfBloco21.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco21.setText("6");
        tfBloco21.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 51), 2, true));
        getContentPane().add(tfBloco21, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 60, 60));

        tfBloco22.setEditable(false);
        tfBloco22.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        tfBloco22.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco22.setText("5");
        tfBloco22.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 2, true));
        getContentPane().add(tfBloco22, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 60, 60));

        tfBloco5.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        tfBloco5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 51), 2, true));
        tfBloco5.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        getContentPane().add(tfBloco5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 60, 60));

        tfBloco6.setEditable(false);
        tfBloco6.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        tfBloco6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco6.setText("1");
        tfBloco6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 51), 2, true));
        getContentPane().add(tfBloco6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 60, 60));

        tfBloco11.setEditable(false);
        tfBloco11.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        tfBloco11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco11.setText("5");
        tfBloco11.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 51), 2, true));
        tfBloco11.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        getContentPane().add(tfBloco11, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 60, 60));

        tfBloco12.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        tfBloco12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco12.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 51), 2, true));
        getContentPane().add(tfBloco12, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 60, 60));

        tfBloco17.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        tfBloco17.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco17.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 2, true));
        getContentPane().add(tfBloco17, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 60, 60));

        tfBloco18.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        tfBloco18.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco18.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 2, true));
        tfBloco18.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        getContentPane().add(tfBloco18, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, 60, 60));

        tfBloco23.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        tfBloco23.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco23.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 2, true));
        getContentPane().add(tfBloco23, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 60, 60));

        tfBloco24.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        tfBloco24.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco24.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 2, true));
        getContentPane().add(tfBloco24, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 60, 60));

        tfBloco25.setEditable(false);
        tfBloco25.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        tfBloco25.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco25.setText("6");
        tfBloco25.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 153), 2, true));
        getContentPane().add(tfBloco25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 60, 60));

        tfBloco26.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        tfBloco26.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco26.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 153), 2, true));
        tfBloco26.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        getContentPane().add(tfBloco26, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 60, 60));

        tfBloco31.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        tfBloco31.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco31.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 153), 2, true));
        getContentPane().add(tfBloco31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 60, 60));

        tfBloco32.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        tfBloco32.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco32.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 153), 2, true));
        tfBloco32.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        getContentPane().add(tfBloco32, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 60, 60));

        tfBloco27.setEditable(false);
        tfBloco27.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        tfBloco27.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco27.setText("1");
        tfBloco27.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 153), 2, true));
        getContentPane().add(tfBloco27, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 60, 60));

        tfBloco28.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        tfBloco28.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco28.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 51), 2, true));
        tfBloco28.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        getContentPane().add(tfBloco28, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 60, 60));

        tfBloco33.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        tfBloco33.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco33.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 153), 2, true));
        getContentPane().add(tfBloco33, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 60, 60));

        tfBloco34.setEditable(false);
        tfBloco34.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        tfBloco34.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco34.setText("1");
        tfBloco34.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 51), 2, true));
        getContentPane().add(tfBloco34, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 60, 60));

        tfBloco29.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        tfBloco29.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco29.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 51), 2, true));
        getContentPane().add(tfBloco29, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 60, 60));

        tfBloco30.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        tfBloco30.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco30.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 51), 2, true));
        tfBloco30.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        getContentPane().add(tfBloco30, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, 60, 60));

        tfBloco35.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        tfBloco35.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco35.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 51), 2, true));
        getContentPane().add(tfBloco35, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 60, 60));

        tfBloco36.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        tfBloco36.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBloco36.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 51), 2, true));
        getContentPane().add(tfBloco36, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, 60, 60));

        btnApagarTudo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnApagarTudo.setText("Apagar tudo");
        btnApagarTudo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnApagarTudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApagarTudoActionPerformed(evt);
            }
        });
        getContentPane().add(btnApagarTudo, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 330, 130, 40));

        btnVerificar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnVerificar.setText("Verificar");
        btnVerificar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVerificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 330, 130, 40));

        jLabelTitulo.setFont(new java.awt.Font("Snap ITC", 3, 70)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(153, 153, 153));
        jLabelTitulo.setText("SUDOKU");
        getContentPane().add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 410, 70));

        jLabelSubTitulo.setFont(new java.awt.Font("Snap ITC", 2, 24)); // NOI18N
        jLabelSubTitulo.setForeground(new java.awt.Color(153, 153, 153));
        jLabelSubTitulo.setText("MEDIUM");
        getContentPane().add(jLabelSubTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 140, 130, -1));

        jLabelTitulo2.setFont(new java.awt.Font("Snap ITC", 1, 102)); // NOI18N
        jLabelTitulo2.setText("6x6");
        jLabelTitulo2.setOpaque(true);
        getContentPane().add(jLabelTitulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, -1, -1));

        jLabelIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sudoku/sudoku (2).png"))); // NOI18N
        getContentPane().add(jLabelIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, 130, 140));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificarActionPerformed
        boolean espacoEmBranco = isEspacoEmBranco();
        
        if (espacoEmBranco) {
            new EspacoEmBranco(this);
        } else {
            int countAcertos = 0;
            
            if (Integer.parseInt(tfBloco2.getText()) == 5) {
                countAcertos += 1;
            }
            if (Integer.parseInt(tfBloco3.getText()) == 3) {
                countAcertos += 1;
            }
            if (Integer.parseInt(tfBloco4.getText()) == 4) {
                countAcertos += 1;
            }
            if (Integer.parseInt(tfBloco5.getText()) == 6) {
                countAcertos += 1;
            }
            if (Integer.parseInt(tfBloco7.getText()) == 1) {
                countAcertos += 1;
            }
            if (Integer.parseInt(tfBloco8.getText()) == 6) {
                countAcertos += 1;
            }
            if (Integer.parseInt(tfBloco12.getText()) == 2) {
                countAcertos += 1;
            }
            if (Integer.parseInt(tfBloco15.getText()) == 2) {
                countAcertos += 1;
            }
            if (Integer.parseInt(tfBloco16.getText()) == 6) {
                countAcertos += 1;
            }
            if (Integer.parseInt(tfBloco17.getText()) == 1) {
                countAcertos += 1;
            }
            if (Integer.parseInt(tfBloco18.getText()) == 3) {
                countAcertos += 1;
            }
            if (Integer.parseInt(tfBloco20.getText()) == 1) {
                countAcertos += 1;
            }
            if (Integer.parseInt(tfBloco23.getText()) == 2) {
                countAcertos += 1;
            }
            if (Integer.parseInt(tfBloco24.getText()) == 4) {
                countAcertos += 1;
            }
            if (Integer.parseInt(tfBloco26.getText()) == 3) {
                countAcertos += 1;
            }
            if (Integer.parseInt(tfBloco28.getText()) == 2) {
                countAcertos += 1;
            }
            if (Integer.parseInt(tfBloco29.getText()) == 4) {
                countAcertos += 1;
            }
            if (Integer.parseInt(tfBloco30.getText()) == 5) {
                countAcertos += 1;
            }
            if (Integer.parseInt(tfBloco31.getText()) == 4) {
                countAcertos += 1;
            }
            if (Integer.parseInt(tfBloco32.getText()) == 2) {
                countAcertos += 1;
            }
            if (Integer.parseInt(tfBloco33.getText()) == 5) {
                countAcertos += 1;
            }
            if (Integer.parseInt(tfBloco35.getText()) == 3) {
                countAcertos += 1;
            }
            if (Integer.parseInt(tfBloco36.getText()) == 6) {
                countAcertos += 1;
            }
            
            if (countAcertos == 23) {
                if (escolhaUsuario.isDesafio()) {
                    this.dispose();
                    String msg = "PARABÉNS, VOCÊ ACABA DE DESBLOQUEAR A FASE 3";
                    String msg2 = "Quer tentar jogar?";
                    String msg3 = "Em 1986, o Sudoku já era um dos jogos mais vendidos no Japão. No entanto, sua disseminação pelo"
                            + "\nmundo ocorreu no fim da década de 90, quando Wayne Gould, juíz da Nova Zelândia, se fascinou"
                            + "\npelo jogo, se tornando o responsável pela primeira publicação do Sudoku em um jornal britânico,"
                            + "\nimpulsionando a popularidade do quebra-cabeça."
                            + "\n"
                            + "\nCom o passar dos anos, o jogo apareceu em revistas e jornais de inúmeros países e até mesmo"
                            + "\nganhou sua própria revista, a Sudoku Selection, sendo que no Brasil, são as Revistas Coquetel quem"
                            + "\npublicam o jogo desde 2005."
                            + "\n"
                            + "\nMas o Sudoku não se limitou ao papel, já que ainda nos primeiros anos de 2000, Wayne Gould"
                            + "\ntambém fez parte do processo de desenvolvimento de um programa de computador que criava"
                            + "\npartidas de Sudoku de forma instantânea.";
                    pontuacao.vitoriaDesafio(this, new Sudoku9x9("desafio"), msg, msg2, msg3);
                } else if (escolhaUsuario.isIndividual()) {
                    pontuacao.vitoriaIndividual(this);
                }
            } else {
                JOptionPane.showMessageDialog(this, "QUE PENA, TENTE NOVAMENTE");
                apagarBlocos();
            }
        }
    }//GEN-LAST:event_btnVerificarActionPerformed

    private void btnApagarTudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagarTudoActionPerformed
        apagarBlocos();
    }//GEN-LAST:event_btnApagarTudoActionPerformed

    private boolean isEspacoEmBranco() {
        int branco = 0;
        
        if (tfBloco2.getText().isBlank()) {
            branco = 1;
        } 
        if (tfBloco3.getText().isBlank()) {
            branco = 1;
        } 
        if (tfBloco4.getText().isBlank()) {
            branco = 1;
        } 
        if (tfBloco5.getText().isBlank()) {
            branco = 1;
        } 
        if (tfBloco7.getText().isBlank()) {
            branco = 1;
        } 
        if (tfBloco8.getText().isBlank()) {
            branco = 1;
        } 
        if (tfBloco12.getText().isBlank()) {
            branco = 1;
        } 
        if (tfBloco15.getText().isBlank()) {
            branco = 1;
        } 
        if (tfBloco16.getText().isBlank()) {
            branco = 1;
        } 
        if (tfBloco17.getText().isBlank()) {
            branco = 1;
        }
        if (tfBloco18.getText().isBlank()) {
            branco = 1;
        }
        if (tfBloco20.getText().isBlank()) {
            branco = 1;
        }
        if (tfBloco23.getText().isBlank()) {
            branco = 1;
        }
        if (tfBloco24.getText().isBlank()) {
            branco = 1;
        }
        if (tfBloco26.getText().isBlank()) {
            branco = 1;
        }
        if (tfBloco28.getText().isBlank()) {
            branco = 1;
        }
        if (tfBloco29.getText().isBlank()) {
            branco = 1;
        }
        if (tfBloco30.getText().isBlank()) {
            branco = 1;
        }
        if (tfBloco31.getText().isBlank()) {
            branco = 1;
        }
        if (tfBloco32.getText().isBlank()) {
            branco = 1;
        }
        if (tfBloco33.getText().isBlank()) {
            branco = 1;
        }
        if (tfBloco35.getText().isBlank()) {
            branco = 1;
        }
        if (tfBloco36.getText().isBlank()) {
            branco = 1;
        }

        if (branco == 1) {
            return true;
        } else {
            return false;
        }
    }
    
    private void apagarBlocos() {
        tfBloco2.setText("");
        tfBloco3.setText("");
        tfBloco4.setText("");
        tfBloco5.setText("");
        tfBloco7.setText("");
        tfBloco8.setText("");
        tfBloco12.setText("");
        tfBloco15.setText("");
        tfBloco16.setText("");
        tfBloco17.setText("");
        tfBloco18.setText("");
        tfBloco20.setText("");
        tfBloco23.setText("");
        tfBloco24.setText("");
        tfBloco26.setText("");
        tfBloco28.setText("");
        tfBloco29.setText("");
        tfBloco30.setText("");
        tfBloco31.setText("");
        tfBloco32.setText("");
        tfBloco33.setText("");
        tfBloco35.setText("");
        tfBloco36.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.setLookAndFeel(
                javax.swing.UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sudoku6x6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sudoku6x6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sudoku6x6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sudoku6x6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sudoku6x6().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApagarTudo;
    private javax.swing.JButton btnVerificar;
    private javax.swing.JLabel jLabelIcon;
    private javax.swing.JLabel jLabelSubTitulo;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelTitulo2;
    private javax.swing.JTextField tfBloco1;
    private javax.swing.JTextField tfBloco10;
    private javax.swing.JTextField tfBloco11;
    private javax.swing.JTextField tfBloco12;
    private javax.swing.JTextField tfBloco13;
    private javax.swing.JTextField tfBloco14;
    private javax.swing.JTextField tfBloco15;
    private javax.swing.JTextField tfBloco16;
    private javax.swing.JTextField tfBloco17;
    private javax.swing.JTextField tfBloco18;
    private javax.swing.JTextField tfBloco19;
    private javax.swing.JTextField tfBloco2;
    private javax.swing.JTextField tfBloco20;
    private javax.swing.JTextField tfBloco21;
    private javax.swing.JTextField tfBloco22;
    private javax.swing.JTextField tfBloco23;
    private javax.swing.JTextField tfBloco24;
    private javax.swing.JTextField tfBloco25;
    private javax.swing.JTextField tfBloco26;
    private javax.swing.JTextField tfBloco27;
    private javax.swing.JTextField tfBloco28;
    private javax.swing.JTextField tfBloco29;
    private javax.swing.JTextField tfBloco3;
    private javax.swing.JTextField tfBloco30;
    private javax.swing.JTextField tfBloco31;
    private javax.swing.JTextField tfBloco32;
    private javax.swing.JTextField tfBloco33;
    private javax.swing.JTextField tfBloco34;
    private javax.swing.JTextField tfBloco35;
    private javax.swing.JTextField tfBloco36;
    private javax.swing.JTextField tfBloco4;
    private javax.swing.JTextField tfBloco5;
    private javax.swing.JTextField tfBloco6;
    private javax.swing.JTextField tfBloco7;
    private javax.swing.JTextField tfBloco8;
    private javax.swing.JTextField tfBloco9;
    // End of variables declaration//GEN-END:variables
}
