/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sudoku;

import javax.swing.JOptionPane;

/**
 *
 * @author laura
 */
public class TelaOpcoes extends javax.swing.JFrame {
    /**
     * Creates new form telaOpcoes
     */
    public TelaOpcoes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEasySudoku4x4 = new javax.swing.JButton();
        btnMediumSudoku4x4 = new javax.swing.JButton();
        btnHardSudoku4x4 = new javax.swing.JButton();
        btnMediumSudoku6x6 = new javax.swing.JButton();
        btnHardSudoku9x9 = new javax.swing.JButton();
        jLabelTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Jogos");
        setPreferredSize(new java.awt.Dimension(335, 350));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEasySudoku4x4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnEasySudoku4x4.setText("Sudoku 4x4 - fácil");
        btnEasySudoku4x4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEasySudoku4x4ActionPerformed(evt);
            }
        });
        getContentPane().add(btnEasySudoku4x4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 220, 35));

        btnMediumSudoku4x4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnMediumSudoku4x4.setText("Sudoku 4x4 - médio");
        btnMediumSudoku4x4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMediumSudoku4x4ActionPerformed(evt);
            }
        });
        getContentPane().add(btnMediumSudoku4x4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 220, 35));

        btnHardSudoku4x4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnHardSudoku4x4.setText("Sudoku 4x4 - difícil");
        btnHardSudoku4x4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHardSudoku4x4ActionPerformed(evt);
            }
        });
        getContentPane().add(btnHardSudoku4x4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 220, 35));

        btnMediumSudoku6x6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnMediumSudoku6x6.setText("Sudoku 6x6 - médio");
        btnMediumSudoku6x6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMediumSudoku6x6ActionPerformed(evt);
            }
        });
        getContentPane().add(btnMediumSudoku6x6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 220, 35));

        btnHardSudoku9x9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnHardSudoku9x9.setText("Sudoku 9x9 - difícil");
        btnHardSudoku9x9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHardSudoku9x9ActionPerformed(evt);
            }
        });
        getContentPane().add(btnHardSudoku9x9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 220, 35));

        jLabelTitulo.setFont(new java.awt.Font("Snap ITC", 1, 48)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(153, 153, 153));
        jLabelTitulo.setText("Opções");
        getContentPane().add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEasySudoku4x4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEasySudoku4x4ActionPerformed
        this.dispose();
        NivelFacil1 sudoku4x4 = new NivelFacil1("individual");
        sudoku4x4.setVisible(true);
        sudoku4x4.setTitle("Sudoku 4x4 Fácil");
    }//GEN-LAST:event_btnEasySudoku4x4ActionPerformed

    private void btnMediumSudoku4x4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMediumSudoku4x4ActionPerformed
        this.dispose();
        NivelMedio1 sudoku4x4 = new NivelMedio1("individual");
        sudoku4x4.setVisible(true);
        sudoku4x4.setTitle("Sudoku 4x4 Médio");
    }//GEN-LAST:event_btnMediumSudoku4x4ActionPerformed

    private void btnHardSudoku4x4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHardSudoku4x4ActionPerformed
        this.dispose();
        NivelDificil1 sudoku4x4 = new NivelDificil1("individual");
        sudoku4x4.setVisible(true);
        sudoku4x4.setTitle("Sudoku 4x4 Difícil");
    }//GEN-LAST:event_btnHardSudoku4x4ActionPerformed

    private void btnMediumSudoku6x6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMediumSudoku6x6ActionPerformed
        this.dispose();
        Sudoku6x6 sudoku6x6 = new Sudoku6x6("individual");
        sudoku6x6.setVisible(true);
        sudoku6x6.setTitle("Sudoku 6x6 Médio");
    }//GEN-LAST:event_btnMediumSudoku6x6ActionPerformed

    private void btnHardSudoku9x9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHardSudoku9x9ActionPerformed
        this.dispose();
        Sudoku9x9 sudoku9x9 = new Sudoku9x9("individual");
        sudoku9x9.setVisible(true);
        sudoku9x9.setTitle("Sudoku 9x9 Difícil");
    }//GEN-LAST:event_btnHardSudoku9x9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.setLookAndFeel(
                javax.swing.UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaOpcoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaOpcoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaOpcoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaOpcoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaOpcoes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEasySudoku4x4;
    private javax.swing.JButton btnHardSudoku4x4;
    private javax.swing.JButton btnHardSudoku9x9;
    private javax.swing.JButton btnMediumSudoku4x4;
    private javax.swing.JButton btnMediumSudoku6x6;
    private javax.swing.JLabel jLabelTitulo;
    // End of variables declaration//GEN-END:variables
}
